#add() = adds an element to the set
#clear() = removes all the elements from the set
#copy() = creates a copy of the set     
#difference() = returns the difference between two or more sets
#difference_update() = removes the elements found in another set from the current set
#discard() = removes the specified element from the set
#intersection() = returns the intersection of two sets
#intersection_update() = removes the elements that are not common to both sets
#isdisjoint() = returns True if two sets have no elements in common
#issubset() = returns True if all elements of a set are present in another set
#issuperset() = returns True if a set contains all elements of another set
#pop() = removes and returns an arbitrary element from the set
#remove() = removes the specified element from the set
#symmetric_difference() = returns the symmetric difference of two sets
#symmetric_difference_update() = updates a set with the symmetric difference of itself and another set
#union() = returns the union of two sets
#update() = updates a set with the union of itself and another set